### ISSUE TITLE
当前版本1.2.64.1不能下载指数，只支持股票和期货的数据...盼解决...

### ISSUE THREAD

**Issue by alxbj** [vnpy/vnpy_tushare#7]
![image](https://user-images.githubusercontent.com/44975835/142091647-423e3069-2bd9-445f-9b13-2faf8cf68238.png)
例如，上证指数...

**Comment by Edanflame** [comment]
感谢关注，已在https://github.com/vnpy/vnpy_tushare/pull/6 中添加
